//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.12.12 at 09:50:26 PM MEZ 
//


package org.openengsb.issues.common.pojos;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import biz.futureware.mantisconnect.CustomFieldValueForIssueData;


/**
 * <p>Java class for CustomFieldValueForIssueDataArray complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CustomFieldValueForIssueDataArray">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://futureware.biz/mantisconnect}CustomFieldValueForIssueData" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CustomFieldValueForIssueDataArray", propOrder = {
    "customFieldValueForIssueData"
})
public class CustomFieldValueForIssueDataArray {

    @XmlElement(name = "CustomFieldValueForIssueData", namespace = "http://futureware.biz/mantisconnect")
    protected List<CustomFieldValueForIssueData> customFieldValueForIssueData;

    /**
     * Gets the value of the customFieldValueForIssueData property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the customFieldValueForIssueData property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCustomFieldValueForIssueData().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CustomFieldValueForIssueData }
     * 
     * 
     */
    public List<CustomFieldValueForIssueData> getCustomFieldValueForIssueData() {
        if (customFieldValueForIssueData == null) {
            customFieldValueForIssueData = new ArrayList<CustomFieldValueForIssueData>();
        }
        return this.customFieldValueForIssueData;
    }

}
