//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.12.12 at 09:50:26 PM MEZ 
//


package org.openengsb.issues.common.pojos;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="account_data" type="{http://common.issues.openengsb.org/pojos}AccountDataType"/>
 *         &lt;element name="issue_id" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="issue_data" type="{http://common.issues.openengsb.org/pojos}IssueDataType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "accountData",
    "issueId",
    "issueData"
})
@XmlRootElement(name = "issue_update_message")
public class IssueUpdateMessage {

    @XmlElement(name = "account_data", required = true)
    protected AccountDataType accountData;
    @XmlElement(name = "issue_id")
    protected int issueId;
    @XmlElement(name = "issue_data", required = true)
    protected IssueDataType issueData;

    /**
     * Gets the value of the accountData property.
     * 
     * @return
     *     possible object is
     *     {@link AccountDataType }
     *     
     */
    public AccountDataType getAccountData() {
        return accountData;
    }

    /**
     * Sets the value of the accountData property.
     * 
     * @param value
     *     allowed object is
     *     {@link AccountDataType }
     *     
     */
    public void setAccountData(AccountDataType value) {
        this.accountData = value;
    }

    /**
     * Gets the value of the issueId property.
     * 
     */
    public int getIssueId() {
        return issueId;
    }

    /**
     * Sets the value of the issueId property.
     * 
     */
    public void setIssueId(int value) {
        this.issueId = value;
    }

    /**
     * Gets the value of the issueData property.
     * 
     * @return
     *     possible object is
     *     {@link IssueDataType }
     *     
     */
    public IssueDataType getIssueData() {
        return issueData;
    }

    /**
     * Sets the value of the issueData property.
     * 
     * @param value
     *     allowed object is
     *     {@link IssueDataType }
     *     
     */
    public void setIssueData(IssueDataType value) {
        this.issueData = value;
    }

}
