//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.12.21 at 02:33:54 AM MEZ 
//


package org.openengsb.issues.common.pojos;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.openengsb.issues.common.pojos package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _IssueNoteData_QNAME = new QName("http://common.issues.openengsb.org/pojos", "IssueNoteData");
    private final static QName _CustomFieldValueForIssueData_QNAME = new QName("http://common.issues.openengsb.org/pojos", "CustomFieldValueForIssueData");
    private final static QName _AttachmentData_QNAME = new QName("http://common.issues.openengsb.org/pojos", "AttachmentData");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.openengsb.issues.common.pojos
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link AttachmentData }
     * 
     */
    public AttachmentData createAttachmentData() {
        return new AttachmentData();
    }

    /**
     * Create an instance of {@link IssueDataType }
     * 
     */
    public IssueDataType createIssueDataType() {
        return new IssueDataType();
    }

    /**
     * Create an instance of {@link IssueUpdateMessage }
     * 
     */
    public IssueUpdateMessage createIssueUpdateMessage() {
        return new IssueUpdateMessage();
    }

    /**
     * Create an instance of {@link CustomFieldValueForIssueData }
     * 
     */
    public CustomFieldValueForIssueData createCustomFieldValueForIssueData() {
        return new CustomFieldValueForIssueData();
    }

    /**
     * Create an instance of {@link UserCredentials }
     * 
     */
    public UserCredentials createUserCredentials() {
        return new UserCredentials();
    }

    /**
     * Create an instance of {@link AttachmentDataArray }
     * 
     */
    public AttachmentDataArray createAttachmentDataArray() {
        return new AttachmentDataArray();
    }

    /**
     * Create an instance of {@link IssueNoteData }
     * 
     */
    public IssueNoteData createIssueNoteData() {
        return new IssueNoteData();
    }

    /**
     * Create an instance of {@link IssueCreateMessage }
     * 
     */
    public IssueCreateMessage createIssueCreateMessage() {
        return new IssueCreateMessage();
    }

    /**
     * Create an instance of {@link CustomFieldValueForIssueDataArray }
     * 
     */
    public CustomFieldValueForIssueDataArray createCustomFieldValueForIssueDataArray() {
        return new CustomFieldValueForIssueDataArray();
    }

    /**
     * Create an instance of {@link AccountData }
     * 
     */
    public AccountData createAccountData() {
        return new AccountData();
    }

    /**
     * Create an instance of {@link IssueDeleteMessage }
     * 
     */
    public IssueDeleteMessage createIssueDeleteMessage() {
        return new IssueDeleteMessage();
    }

    /**
     * Create an instance of {@link ObjectRef }
     * 
     */
    public ObjectRef createObjectRef() {
        return new ObjectRef();
    }

    /**
     * Create an instance of {@link IssueNoteDataArray }
     * 
     */
    public IssueNoteDataArray createIssueNoteDataArray() {
        return new IssueNoteDataArray();
    }

    /**
     * Create an instance of {@link IssueGetMessage }
     * 
     */
    public IssueGetMessage createIssueGetMessage() {
        return new IssueGetMessage();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link IssueNoteData }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://common.issues.openengsb.org/pojos", name = "IssueNoteData")
    public JAXBElement<IssueNoteData> createIssueNoteData(IssueNoteData value) {
        return new JAXBElement<IssueNoteData>(_IssueNoteData_QNAME, IssueNoteData.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CustomFieldValueForIssueData }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://common.issues.openengsb.org/pojos", name = "CustomFieldValueForIssueData")
    public JAXBElement<CustomFieldValueForIssueData> createCustomFieldValueForIssueData(CustomFieldValueForIssueData value) {
        return new JAXBElement<CustomFieldValueForIssueData>(_CustomFieldValueForIssueData_QNAME, CustomFieldValueForIssueData.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AttachmentData }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://common.issues.openengsb.org/pojos", name = "AttachmentData")
    public JAXBElement<AttachmentData> createAttachmentData(AttachmentData value) {
        return new JAXBElement<AttachmentData>(_AttachmentData_QNAME, AttachmentData.class, null, value);
    }

}
